controller_list:
  - name: fake_left_arm_controller
    joints:
      - limb_left_joint1
      - limb_left_joint2
      - limb_left_joint3
      - limb_left_joint4
      - limb_left_joint5
      - limb_left_joint6
      - limb_left_joint7
  - name: fake_right_arm_controller
    joints:
      - limb_right_joint1
      - limb_right_joint2
      - limb_right_joint3
      - limb_right_joint4
      - limb_right_joint5
      - limb_right_joint6
      - limb_right_joint7
  - name: fake_left_gripper_controller
    joints:
      - limb_left_joint7
  - name: fake_right_gripper_controller
    joints:
      - limb_right_joint7