base_front_offset_x: -0.37 #-0.49

arm_front_offset_x: 0.3
arm_front_offset_y: -0.5  # -1.1, 0.0
arm_length: 0.5           # 1.5
arm_length_core: 0.3      # 0.5

body_length: 0.5          # 0.8
body_length_core: 0.335   # 0.65

sampling:
  dist_min: 0.4 #0.5
  dist_step: 0.1
  dist_count: 6

  ang_min: 0.0
  ang_step: 15.0
  ang_count: 24

  yaw_min: -20.0
  yaw_step: 5.0
  yaw_count: 9

exhaustive_sampling:
  dist_min: 0.4 #0.5
  dist_step: 0.1
  dist_count: 6

  ang_min: 0.0
  ang_step: 30.0
  ang_count: 12

  yaw_min: -5.0 #-20.0
  yaw_step: 5.0
  yaw_count: 3 #9

grasping:
  best_dist: 0.6 #0.7

exhaustive_grasping:
  best_dist: 0.6

max_grasp_candidates: 20
manipulator_group_name: right_arm
footprint:
  - { x: -0.6, y: -0.4 }
  - { x:  0.6, y: -0.4 }
  - { x:  0.6, y:  0.4 }
  - { x: -0.6, y:  0.4 }
