robot_collision_model:
  voxels_models:
    - link_name: talon
    - link_name: torso_link0
    - link_name: chest

    # links with trivial or no geometry (stated here for reference)
    - link_name: base_footprint
    - link_name: base_link
    - link_name: track_left
    - link_name: track_right

  spheres_models:
    - link_name: torso_link0
      auto: false
      radius: 0.02
      spheres:
        - { name: t0, x: 0.5, y: 0.0, z: 0.0, radius: 0.15 }
        - { name: t1, x: 0.42, y: 0.0, z: 0.0, radius: 0.15 }
        - { name: t2, x: 0.35, y: 0.16, z: 0.05, radius: 0.08 }
        - { name: t3, x: 0.35, y: 0.16, z: -0.05, radius: 0.08 }
    - link_name: chest
      auto: false
      radius: 0.02
      spheres:
        - { name: c01, x: 0.00, y: -0.12, z: -0.12, radius: 0.08 }
        - { name: c02, x: 0.00, y:  0.00, z: -0.12, radius: 0.08 }
        - { name: c03, x: 0.00, y:  0.12, z: -0.12, radius: 0.08 }
        - { name: c04, x: 0.00, y: -0.12, z:  0.0,  radius: 0.08 }
        - { name: c05, x: 0.00, y:  0.00, z:  0.0,  radius: 0.08 }
        - { name: c06, x: 0.00, y:  0.12, z:  0.0,  radius: 0.08 }
        - { name: c07, x: 0.00, y: -0.12, z:  0.12, radius: 0.08 }
        - { name: c08, x: 0.00, y:  0.00, z:  0.12, radius: 0.08 }
        - { name: c09, x: 0.00, y:  0.12, z:  0.12, radius: 0.08 }
        - { name: c10, x: 0.00, y: -0.19, z:  0.185, radius: 0.02 }
        - { name: c10, x: 0.00, y: -0.16, z:  0.185, radius: 0.02 }
        - { name: c10, x: 0.00, y: -0.13, z:  0.185, radius: 0.02 }
        - { name: c10, x: 0.00, y: -0.10, z:  0.185, radius: 0.02 }
        - { name: c10, x: 0.00, y: -0.07, z:  0.185, radius: 0.02 }
        - { name: c10, x: 0.00, y: -0.04, z:  0.185, radius: 0.02 }
        - { name: c12, x: 0.00, y: -0.19, z: -0.185, radius: 0.02 }
        - { name: h00, x: 0.20, y:  0.03, z:  0.13, radius: 0.08 }
        - { name: h01, x: 0.20, y:  0.03, z: -0.13, radius: 0.08 }
        - { name: h02, x: 0.20, y:  0.03, z:  0.00, radius: 0.08 }
        - { name: a01, x: 0.05, y: -0.16, z:  0.04, radius: 0.11 }
    - link_name: limb_left_link0
      auto: false
      radius: 0.02
      spheres:
        - { name: ll0s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link1
      auto: false
      radius: 0.02
      spheres:
        - { name: ll1s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link2
      auto: false
      radius: 0.02
      spheres:
        - { name: ll2s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link3
      auto: false
      radius: 0.02
      spheres:
        - { name: ll3s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link4
      auto: false
      radius: 0.02
      spheres:
        - { name: ll4s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link5
      auto: false
      radius: 0.02
      spheres:
        - { name: ll5s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link6
      auto: false
      radius: 0.02
      spheres:
        - { name: ll6s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_left_link7
      auto: false
      radius: 0.02
      spheres:
        - { name: ll7s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
#    - link_name: limb_right_link0
#      spheres:
#        - { name: lr0s0, x: 0.0, y: 0.0, z: 0.0, radius: 0.05 }
    - link_name: limb_right_link1
      auto: false
      radius: 0.02
      spheres:
#        - { name: lr1s0, x: -0.06, y: 0.0, z: 0.0, radius: 0.06 }
        - { name: lr1s0, x:  0.00, y: 0.0, z: 0.0, radius: 0.055 }
    - link_name: limb_right_link2
      auto: false
      radius: 0.02
      spheres:
        - { name: lr2s0, x: 0.000, y: -0.06, z: 0.0, radius: 0.055 }
        - { name: lr2s1, x: 0.000, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr2s2, x: 0.045, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr2s3, x: 0.090, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr2s4, x: 0.135, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr2s5, x: 0.180, y: -0.12, z: 0.0, radius: 0.055 }
    - link_name: limb_right_link3
      auto: false
      radius: 0.02
      spheres:
        - { name: lr3s0, x: -0.06, y: 0.0, z: 0.0, radius: 0.055 }
        - { name: lr3s0, x:  0.00, y: 0.0, z: 0.0, radius: 0.055 }
    - link_name: limb_right_link4
      auto: false
      radius: 0.02
      spheres:
        - { name: lr4s0, x: 0.000, y: -0.06, z: 0.0, radius: 0.055 }
        - { name: lr4s1, x: 0.000, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr4s2, x: 0.045, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr4s3, x: 0.090, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr4s4, x: 0.135, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr4s5, x: 0.180, y: -0.12, z: 0.0, radius: 0.055 }
    - link_name: limb_right_link5
      auto: false
      radius: 0.02
      spheres:
        - { name: lr5s0, x: -0.06, y: 0.0, z: 0.0, radius: 0.055 }
        - { name: lr5s0, x:  0.00, y: 0.0, z: 0.0, radius: 0.055 }
    - link_name: limb_right_link6
      auto: false
      radius: 0.02
      spheres:
        - { name: lr6s0, x: 0.000, y: -0.06, z: 0.0, radius: 0.055 }
        - { name: lr6s1, x: 0.000, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr6s2, x: 0.045, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr6s3, x: 0.090, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr6s4, x: 0.135, y: -0.12, z: 0.0, radius: 0.055 }
        - { name: lr6s5, x: 0.180, y: -0.12, z: 0.0, radius: 0.055 }
    - link_name: limb_right_link7
      auto: false
      radius: 0.02
      spheres:
        - { name: lr7s0, x: 0.165, y: 0.0, z: 0.0, radius: 0.13 }
  collision_groups:
    - name: left_arm
      links:
        - name: limb_left_link0
        - name: limb_left_link1
        - name: limb_left_link2
        - name: limb_left_link3
        - name: limb_left_link4
        - name: limb_left_link5
        - name: limb_left_link6
        - name: limb_left_link7
    - name: right_arm
      links:
        - name: limb_right_link0
        - name: limb_right_link1
        - name: limb_right_link2
        - name: limb_right_link3
        - name: limb_right_link4
        - name: limb_right_link5
        - name: limb_right_link6
        - name: limb_right_link7
    - name: right_arm_and_torso
      links:
        - name: limb_right_link0
        - name: limb_right_link1
        - name: limb_right_link2
        - name: limb_right_link3
        - name: limb_right_link4
        - name: limb_right_link5
        - name: limb_right_link6
        - name: limb_right_link7
        - name: torso_link0
        - name: chest
