sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: base_scan_filtered
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud
  - sensor_plugin: roman_moveit_plugins/OctomapOccupancyMapUpdater
    octomap_topic: octomap_binary
