degree: 3

control_points: [
    { x: -0.9970, y: 0.629, z: 0.01690 },
    { x: -1.0020, y: 0.695, z: 0.02060 },
    { x: -0.9640, y: 0.966, z: 0.01540 },
    { x: -0.8960, y: 1.084, z: 0.01780 },
    { x: -0.7700, y: 1.249, z: 0.01270 },
    { x: -0.6150, y: 1.341, z: 0.00939 },
    { x: -0.5000, y: 1.378, z: 0.00939 },
    { x: -0.4210, y: 1.384, z: 0.01360 },
    { x: -0.2925, y: 1.396, z: 0.01320 },
    { x:  0.0370, y: 1.412, z: 0.00000 },
    { x:  0.2320, y: 1.374, z: 0.00000 },
    { x:  0.2550, y: 1.364, z: 0.00000 },
    { x:  0.2670, y: 1.357, z: 0.00000 }
]

