wrist_to_tool_transform:
    position:
        x: 0.06
        y: 0.0
        z: 0.0
    orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0

pregrasp_to_grasp_offset_m: 0.08

stow_positions:
    - { name: "one", joint_vector_degs: [ 92.00, 84.00, -102.00, 59.00, 77.0, 1.00, -24.00 ] }
    - { name: "two", joint_vector_degs: [ -78.00, -42.00, 11.00, 29.00, 9.00, 10.00, -29.00 ] }

max_grasp_candidates: 4 # the number of grasps to attempt to plan to
