# describe convenience frame from the object frame to the footprint of the object
object_footprint_x_m: 0.0
object_footprint_y_m: -0.10 #0.172
object_footprint_z_m: 0.0
object_footprint_roll_deg: -90.0
object_footprint_pitch_deg: 0.0
object_footprint_yaw_deg: 0.0

# describe transform from the world frame to the 'room' frame
world_frame_name: "abs_nwu"
room_frame_x_m: 2.0
room_frame_y_m: 9.0
room_frame_yaw_deg: -9.5

# describe the initial pose of the robot in the frame of the 'room'
robot_initial_x_m: 1.5
robot_initial_y_m: 8.0
robot_initial_yaw_deg: 0.0

# describe the initial joint state for the hdt
robot_initial_joint_values: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

# describe the dimensions and frame of the room, for sampling object poses
room_length_m: 7.0
room_width_m: 9.5
num_disc_x: 8
num_disc_y: 10
num_disc_yaw: 4
