controller_list:
    - name: right_limb
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - limb_right_joint1
        - limb_right_joint2
        - limb_right_joint3
        - limb_right_joint4
        - limb_right_joint5
        - limb_right_joint6
        - limb_right_joint7
    - name: left_limb
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - limb_left_joint1
        - limb_left_joint2
        - limb_left_joint3
        - limb_left_joint4
        - limb_left_joint5
        - limb_left_joint6
        - limb_left_joint7
    - name: right_gripper
      action_ns: gripper_action
      type: GripperCommand
      default: true
      joints: []
