right_arm:
  planner_configs:
    - name: right_arm_ARA_BFS_ML
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_ARA_BFS_WS
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmWorkspaceConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_ARA_JD_ML
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_MHA_BFS_ML
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_LARA_BFS_ML
      search_config: LARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: egwastar.bfs_egraph.manip_egraph
      search_config: EGWAConfigDefault
      heuristic_config: BFSEGraphConfig
      graph_config: RightArmManipLatticeEgraphConfigDefault
      shortcut_config: PVJointConfigDefault

right_arm_and_torso:
  planner_configs:
    - name: right_arm_and_torso_ARA_BFS_ML
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_and_torso_ARA_JD_ML
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_and_torso_MHA_BFS_ML
      search_config: MHAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    - name: right_arm_and_torso_LARA_BFS_ML
      search_config: LARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault

search_configs:
  ARAConfigDefault:
    search: arastar
    epsilon: 100.0
  MHAConfigDefault:
    search: mhastar
    epsilon: 100.0
    mha_epsilon: 100.0
  LARAConfigDefault:
    search: larastar
    epsilon: 100.0
  EGWAConfigDefault:
    search: egwastar
    epsilon: 100.0

heuristic_configs:
  BFSConfigDefault:
    heuristic: bfs
    bfs_res_x: 0.015
    bfs_res_y: 0.015
    bfs_res_z: 0.015
    bfs_sphere_radius: 0.02
  BFSEGraphConfig:
    heuristic: bfs_egraph
    bfs_res_x: 0.015
    bfs_res_y: 0.015
    bfs_res_z: 0.015
    egraph_epsilon: 20.0
    bfs_sphere_radius: 0.02
  JointDistConfigDefault:
    heuristic: joint_distance

graph_configs:
  RightArmManipLatticeConfigDefault:
    graph: manip
    discretization:
      limb_right_joint1: 0.017453292519943
      limb_right_joint2: 0.017453292519943
      limb_right_joint3: 0.017453292519943
      limb_right_joint4: 0.017453292519943
      limb_right_joint5: 0.017453292519943
      limb_right_joint6: 0.017453292519943
      limb_right_joint7: 0.017453292519943
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  RightArmManipLatticeEgraphConfigDefault:
    graph: manip_lattice_egraph
    discretization:
      limb_right_joint1: 0.017453292519943
      limb_right_joint2: 0.017453292519943
      limb_right_joint3: 0.017453292519943
      limb_right_joint4: 0.017453292519943
      limb_right_joint5: 0.017453292519943
      limb_right_joint6: 0.017453292519943
      limb_right_joint7: 0.017453292519943
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
    egraph_path: /home/aurone/.ros/egraph_paths
  RightArmWorkspaceConfigDefault:
    graph: workspace
  RightArmAndTorsoManipLatticeConfigDefault:
    graph: manip
    # angular resolution of each active joint variable
    discretization:
      limb_right_joint1: 0.017453292519943
      limb_right_joint2: 0.017453292519943
      limb_right_joint3: 0.017453292519943
      limb_right_joint4: 0.017453292519943
      limb_right_joint5: 0.017453292519943
      limb_right_joint6: 0.017453292519943
      limb_right_joint7: 0.017453292519943
      torso_joint1: 0.017453292519943
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4

shortcut_configs:
  PVJointConfigDefault:
    shortcut_path: true
    shortcutter: joint_position_velocity_space
    interpolate_path: true
